### ISSUE TITLE
fix travis

### ISSUE THREAD

**Issue by axyz** [axyz/optimal-image#7]
@addityasingh I activated basic travis support, but some fmt lints are different from nightly and stable...

not sure if that can be easily fixed, also don't know if it needed to run build or if cargo check may be enough to save time.

**Comment by addityasingh** [comment]
IMO, we should find a stable version and freeze that in travis to avoid dealing with unavoidable issues with builds breaking

For the build part I think `cargo check` should be enough for the correctness checks

I have created a quick PR here (https://github.com/axyz/optimal-image/pull/8)
